language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: QafDqB4mUzHx593Fhc4jhkUDdv4TUAGZkUyXioS0kR/8JQGO0hYeCRfDKYA38N6FZb8Pb0MNEjheEDb6QMNEuMVo05S5ti1yWbJg+ZJunACEpmHAO5lqZefkwOamh5oLTQLMZjFvlu7yRngOhz1G+HzpT5bMx1RVdMk5jV+7+qcAJTAcP+bBQAzk40ylerMgMapgjh+eGuWbEP5sDPONnB8ZF4iFfUm61uTfw7/8KGr0KyjHunFySu1WsPGIAXEWx0OrM7FTHTjg5tWJ12UN7O+XaYArz314kYDQ3v5fDtnVVyDDKzeUneyarbCSKyu3/ikcEYUJFO00jJDmxPe39aXibOn8cqY8b5z4BMhTHaGorM0nLbHtuVmuZom/Dx1iVpwaQlkFxaUTkUZx1rd2NX2m5of/NMMNVGu0YCpiQrDQ1elGweNKuTtGobVgHFHT3ZqZK+RH4EnujJRDknrQqWZ5BDMOecyLO2YdO4YsBXSXcCAywMplc46GCm7rNER6ScuAntYjdmNCLHjpw/r8p1Py9Mo8+G2BKkoin2iPF6iIm2y3IxEA/BxHmU3TJFIHLBgk/aOWvco4Y+3yVEeoQ8bxNiW6shsmYpbGItSGOtCFyrBRr55dYkKuSMHw+4ORsnA/2WUQozTePNUdnCrj5nLxIwqs5/a8XJtKIjZ8URQ=
  app: localtester
cache:
  directories:
    - node_modules